### ISSUE TITLE
Improve statue-card layout

### ISSUE THREAD

**Issue by iuliaghindeanu** [ionutpetre/bucharest-statues#1]
Instead of writing the category of the statue by it's name, put it under the left-down corner

![image](https://cloud.githubusercontent.com/assets/12461294/20648343/b713d9e4-b4ac-11e6-9745-71dc9301a805.png)

**Comment by ionutpetre** [comment]
Thank you for your feed-back, @iuliaghindeanu. I've added this in our to do list! :)

**Comment by ionutpetre** [comment]
Resolved in this https://github.com/ionutpetre/bucharest-statues/commit/f543398427e1d409878eeb93722377d8464fdfe9
