### ISSUE TITLE
Add return button from Statue Details back to All Statues

### ISSUE THREAD

**Issue by iuliaghindeanu** [ionutpetre/bucharest-statues#2]
![image](https://cloud.githubusercontent.com/assets/12461294/20648422/3dd0366a-b4af-11e6-8d77-4d3027e8e700.png)

**Comment by ionutpetre** [comment]
Resolved in this commit: https://github.com/ionutpetre/bucharest-statues/commit/c7149f1a0ba327491beda872c57f4dd84324bfb2
